fix(android): Be able to disable the subtitles
bcc-code/bcc-media-app pull request #127
Opened 2023-05-03 19:51 UTC by cj-wessels

## About the changes

### Important files

## Discussion points

2023-05-04 13:18 UTC, andreasgan requested changes
Great that you found a solution 🎉

2023-05-04 13:18 UTC, andreasgan commented on external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/players/exoplayer/ExoPlayerController.kt
> -            .setPreferredAudioLanguage(appConfigState?.audioLanguage)
Looks like you removed audio selection by accident

2023-05-04 13:18 UTC, andreasgan commented on external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/players/exoplayer/ExoPlayerController.kt
> +        if (textLanguageThatShouldBeSelected == null) {
Suggestion
- rename this to setTextTrack
- move the "run only once"-logic into `onTracksChanged`

2023-05-04 13:18 UTC, andreasgan commented on external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/players/exoplayer/ExoPlayerController.kt
> +        if (textLanguageThatShouldBeSelected == null) {
would make it more readable whats going on

2023-05-04 15:40 UTC, andreasgan commented
Fixes #128

2023-05-15 07:05 UTC, andreasgangso approved these changes

2023-05-15 07:07 UTC, merged